### ISSUE TITLE
Set cell open or closed on load

### ISSUE THREAD

**Issue by chaseacton** [bennyguitar/CollapseClick#1]
I have two cells in my CollapseClick table. How can I set one to be open by default?

**Comment by bennyguitar** [comment]
I added four new methods to CollapseClick.h/.m

These methods include <code>openCollapseClickCellAtIndex:(int) animated:(BOOL)</code> and <code>closeCollapseClickCellAtIndex:(int) animated:(BOOL)</code>, as well as their counterparts for opening/closing multiple cells at once. To open multiple, you pass in an NSArray of NSNumbers corresponding to the indexes you would like to manipulate. Hope this helps you out, and thanks for raising the issue.
