### ISSUE TITLE
Doesn't work with CocoaPods

### ISSUE THREAD

**Issue by vjpr** [bennyguitar/CollapseClick#14]
After including it I get the following error which fails the build:

```
Unable to run command 'StripNIB CollapseClickCell.nib' - this target might include its own product.
```

**Comment by macinsmithInrix** [comment]
I had this problem too.  I discovered that it must be mentioned in the s.resources specifier

**Comment by zdennis** [comment]
@macinsmithInrix , what do you mean "in the s.resources specifier" ?

**Comment by macinsmithInrix** [comment]
rather than adding a reference to the file in the s.source_files, I put it in the s.resources as shown below

  s.resources = ["images/*.png", "classes/MyView.xib"]

**Comment by ghost** [comment]
Thank you @macinsmithInrix it solved this problem for me too

**Comment by zhujin001032** [comment]
Than you @macinsmithInrix it useful for me

**Comment by devluyy** [comment]
@macinsmithInrix 
thanks, soga

**Comment by LeoMobileDeveloper** [comment]
@macinsmithInrix  Thanks

**Comment by makcimyc92** [comment]
i remove have error in MLDatePicker. I fix error when remove error files from target
<img width="865" alt="screen shot 2017-05-26 at 12 26 39" src="https://cloud.githubusercontent.com/assets/15267414/26489100/ae3ed982-420e-11e7-865c-43f84e2afb72.png">
