### ISSUE TITLE
Best way to access sub cell?

### ISSUE THREAD

**Issue by daviddelmonte** [bennyguitar/CollapseClick#20]
What is the best way to specify and access the cells held by each collapsible cell?  I cannot figure out how to access the subcells.. I can show the number of cells ok, and give the cells titles, etc.

What I can't figure out is how to set data (text, images etc,) into each cell. Any help would be appreciated.

**Comment by daviddelmonte** [comment]
This is probably a dumb question, but could anyone help me with it. offline email is ddelmonte at mac dot com  thank you. i love this control, and would really like to get it to work as a detail view in my project. I cannot figure how to identify each sub cell so I can manipulate the textfield.

**Comment by eldaniel7** [comment]
You should use the delegate method `-(UIView *)viewForCollapseClickContentViewAtIndex:(int)index`

**Comment by daviddelmonte** [comment]
Yep, thanks very much for answering. I have one set of cells set up as a separate class to test. I return that class to the VC. I do not get anything sent from the class to the VC. Any attempt to log in the VC causes a crash. For example, this is set in my class:
- (void)loadElements
  {
  NSLog(@"%s", **FUNCTION**);
  item.text = @"try this";
  category.text = @"category";
  date1.text = @"todays date";
  date2.text = @"another date";
  serial.text = @"serial no";
  }

in viewForCollapseClick....

simply:

switch (index) {
        case 0:
            NSLog(@"itemView: %@", itemView);
            //NSLog(@"itemView: %@", itemView.item.text);
            // itemView.item.text = @"newTest";
            return itemView;
            break;

If I try to log itemView.item.text, I get a crash. I must still be doing something dumb, and would appreciate any ideas. (like post this on SO?)
