### ISSUE TITLE
How can i know which collapsable cell is clicked? No Click event for collapsable cell

### ISSUE THREAD

**Issue by demotesting** [bennyguitar/CollapseClick#3]

**Comment by bennyguitar** [comment]
My laptop's at the Apple Store getting a new logic board right now, but either tomorrow or Wednesday I'll have a delegate method extended for you (and everyone else) to do something on click as well.

**Comment by bennyguitar** [comment]
Just added a delegate method for ya'.

didClickCollapseClickCellAtIndex:(int) isNowOpen:(BOOL)
