### ISSUE TITLE
Multiple screen sizes solution

### ISSUE THREAD

**Issue by AIFanatic** [bennyguitar/CollapseClick#30]
Hello,

The position of the arrow and lightBorder/darkBorder are hardcoded with a width of 320 pixels.
This works fine on 4s/5/5s but when you switch to bigger devices it starts to become a problem, also when the device rotates the position of these elements remains static.

I was able to fix the arrow and borders by changing the following code:

CollapseClickCell.m:newCollapseClickCellWithTitle

`  

```
CGSize screenSize = [[UIScreen mainScreen] bounds].size;
cell.TitleArrow.frame = CGRectMake(screenSize.width-32, 14, 22, 22);
cell.TitleDarkBorder.frame = CGRectMake(0, 49, screenSize.width, 1);
cell.TitleLightBorder.frame = CGRectMake(0, 0, screenSize.width, 1);
```

`

Also linked darkBorder and lightBorder.

The device orientation can be fixed by adding a notification when device rotates.

Hope it helps someone

**Comment by ulises01** [comment]
![captura de pantalla 2018-05-29 a la s 16 01 52](https://user-images.githubusercontent.com/39272359/40687977-9ca31c70-6359-11e8-9599-0f931251a363.png)

how can I adapt the components
