### ISSUE TITLE
set height of a CollapseClick's title view

### ISSUE THREAD

**Issue by miquelalvarado** [bennyguitar/CollapseClick#4]
Hi! It would be great if i could set the height of a CollapsableClick's title view, is there any way to achieve it?

Thanks for your time and your great job

**Comment by ghost** [comment]
I can't able to understand what are trying to explain. Can you explain clearly...

**Comment by miquelalvarado** [comment]
Sorry, look at the screenshot. I have drawn there the zone i want to reduce. Is it possible to get access to the frame of that element and modify its height? Thanks 

![Captura de pantalla 2013-03-27 a la s 08 41 06](https://f.cloud.github.com/assets/3353597/307139/0c1b6b18-96b2-11e2-841f-afa5d6d0bc39.png)

**Comment by ghost** [comment]
In CollapseClickCell.h, change the "kCCHeaderHeight" value to what ever height you want.

**Comment by miquelalvarado** [comment]
Thanks!
